# Generated by Django 3.1.2 on 2020-10-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbox',
            options={'verbose_name': 'Inbox', 'verbose_name_plural': 'Inbox'},
        ),
    ]
