# Generated by Django 3.1.2 on 2020-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
