# Generated by Django 3.1.2 on 2020-10-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tea', 'Tea'), ('Coffee', 'Coffee')], max_length=10),
        ),
    ]
