# Generated by Django 3.1.2 on 2020-10-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201014_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
