# Generated by Django 3.1.2 on 2020-10-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201015_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
