# Generated by Django 3.1.2 on 2020-10-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201015_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='sku',
        ),
    ]
