# Generated by Django 3.1.2 on 2020-10-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201015_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tea',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
