# Generated by Django 3.1.2 on 2020-10-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201020_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flavour'),
        ),
    ]
