# Generated by Django 3.1.2 on 2020-10-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_flavour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='friendly_name',
        ),
    ]
